# Generated by Django 4.2.27 on 2026-06-15 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_faqviewed_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='practice_area_secondary',
        ),
    ]
